name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Update application.yml
        run: |
          echo "$(cat charrypickapp/application.yml | sed 's/active: local/active: prod/')" > charrypickapp/application.yml

      - name: Grant execute permission for gradlew
        working-directory: charrypickapp
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: charrypickapp
        run: ./gradlew clean build
