spring:
  port : 5000
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    datasource:
      url: jdbc:mysql://${RDS_HOST}:3306/cherrypick
      username: ${RDS_USERNAME}
      password: ${RDS_PASSWORD}