spring:
  profiles:
    active: local

---

spring:
  config:
    name: local
    activate:
      on-profile:
  resources:
    config-location: classpath:/application-local.yml

---

spring:
  config:
    name: prod
    activate:
      on-profile:
  resources:
    config-location: classpath:/application-prod.yml
