spring:

  jpa:
    database: mysql
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://database-1.c1ymulo0ueco.ap-northeast-2.rds.amazonaws.com:3306/cherrypick
#    username: admin
#    password: pw123456789
    url: jdbc:mysql://cherrypick-rds.cije20wikun0.ap-northeast-2.rds.amazonaws.com:3306/cherrypick
    username: cherrypick
    password: cherrypick1234!

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  #이 아래로 주석처리하면 H2 인메모리
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/cherrypick
#    username: sa
#    password:
#    driver-class-name: org.h2.Driver
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        format_sql: true
#  logging.level:
#    org.hibernate.SQL: debug